apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
    project: expense
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      name: frontend
      project: expense
  template:
    metadata:
      labels:
        name: frontend
        project: expense
    spec:
      containers:
      - name: frontend
        image: devopsrikanth/frontend:v1.0
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend
          items:
            - key: nginx.conf
              path: nginx.conf

